// <auto-generated />
using System;
using API_AppParkingSoft.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_AppParkingSoft.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20231123005221_updateDB1")]
    partial class updateDB1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API_AppParkingSoft.DAL.Entities.CategoryVehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("typeCategory")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RateId");

                    b.ToTable("CategoryVehicles");
                });

            modelBuilder.Entity("API_AppParkingSoft.DAL.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("clientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("API_AppParkingSoft.DAL.Entities.Rate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("hourlyRate")
                        .HasColumnType("float");

                    b.Property<double>("monthlyRate")
                        .HasColumnType("float");

                    b.Property<double>("weeklyRate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("API_AppParkingSoft.DAL.Entities.Reserve", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FinalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinalHour")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartHour")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalCost")
                        .HasColumnType("float");

                    b.Property<bool>("stateReserve")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Reserves");
                });

            modelBuilder.Entity("API_AppParkingSoft.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<Guid?>("ReserveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("idUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReserveId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API_AppParkingSoft.DAL.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CategoryVehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReserveId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryVehicleId");

                    b.HasIndex("ClientId");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.HasIndex("ReserveId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("API_AppParkingSoft.DAL.Entities.CategoryVehicle", b =>
                {
                    b.HasOne("API_AppParkingSoft.DAL.Entities.Rate", null)
                        .WithMany("CategoriesVehicles")
                        .HasForeignKey("RateId");
                });

            modelBuilder.Entity("API_AppParkingSoft.DAL.Entities.User", b =>
                {
                    b.HasOne("API_AppParkingSoft.DAL.Entities.Reserve", null)
                        .WithMany("users")
                        .HasForeignKey("ReserveId");
                });

            modelBuilder.Entity("API_AppParkingSoft.DAL.Entities.Vehicle", b =>
                {
                    b.HasOne("API_AppParkingSoft.DAL.Entities.CategoryVehicle", "CategoryVehicle")
                        .WithMany()
                        .HasForeignKey("CategoryVehicleId");

                    b.HasOne("API_AppParkingSoft.DAL.Entities.Client", "Client")
                        .WithMany("Vehicles")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_AppParkingSoft.DAL.Entities.Reserve", null)
                        .WithMany("vehicles")
                        .HasForeignKey("ReserveId");

                    b.Navigation("CategoryVehicle");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("API_AppParkingSoft.DAL.Entities.Client", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("API_AppParkingSoft.DAL.Entities.Rate", b =>
                {
                    b.Navigation("CategoriesVehicles");
                });

            modelBuilder.Entity("API_AppParkingSoft.DAL.Entities.Reserve", b =>
                {
                    b.Navigation("users");

                    b.Navigation("vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
